// Archivo de datos pre-cargados por defecto
const defaultDashboardData = {
  "espec": "Ingeniería Civil",
  "materia": "Fundamentos de Informática",
  "comision": "3",
  "anio": "2025",
  "curso": "1C3",
  "edificio": "Edif. Ing.Possetto - Aula 999",
  "students": [
    {
      "legajo": "417313",
      "nombre": "Aguirre Ramirez, Lucas Joaquin",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "No Cursó",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416575",
      "nombre": "Aguirre, Silvana Romina",
      "p1": "4",
      "p2": "2",
      "rec1": null,
      "int1": "10",
      "int2": "67",
      "regProfesor": "Libre",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416717",
      "nombre": "Almada Sanuar, Germán",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "No Cursó",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "422101",
      "nombre": "Almada, Emilio",
      "p1": "2",
      "p2": "84",
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Abandonó",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "421899",
      "nombre": "Altamirano, Gabriel Alejandro",
      "p1": "4",
      "p2": "7",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416882",
      "nombre": "Amaya, Lautaro Gastón",
      "p1": "7",
      "p2": "2",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417398",
      "nombre": "Antonino, Ivo Giuliano",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "No Cursó",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417973",
      "nombre": "Araujo, Juan Cruz",
      "p1": "8",
      "p2": "2",
      "rec1": "4",
      "int1": "10",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417343",
      "nombre": "Bach, Stephan Alexander",
      "p1": "6",
      "p2": "6",
      "rec1": "9",
      "int1": null,
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417220",
      "nombre": "Barboza, Joel Emiliano",
      "p1": "2",
      "p2": "84",
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Abandonó",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416170",
      "nombre": "Barone, Guillermina",
      "p1": "6",
      "p2": "4",
      "rec1": "6",
      "int1": "9",
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "83956",
      "nombre": "Bojaryn Molteni, Agustin Fernando",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "No Cursó",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416360",
      "nombre": "Borgna, Santiago",
      "p1": "8",
      "p2": "4",
      "rec1": "6",
      "int1": "9",
      "int2": "8",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416704",
      "nombre": "Brizuela Waidatt, Katrina Bettiana",
      "p1": "4",
      "p2": "2",
      "rec1": "2",
      "int1": "9",
      "int2": "67",
      "regProfesor": "Libre",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416695",
      "nombre": "Buffa, Augusto Salvador",
      "p1": "4",
      "p2": "4",
      "rec1": "48",
      "int1": null,
      "int2": null,
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418668",
      "nombre": "Buitrago, Sol Agustina",
      "p1": "7",
      "p2": "6",
      "rec1": "9",
      "int1": null,
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418571",
      "nombre": "Bullo, Lucia",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "No Cursó",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "419246",
      "nombre": "Cabrera, María Belén",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416039",
      "nombre": "Calle Cusipuma, Shani Jeziel",
      "p1": "2",
      "p2": "2",
      "rec1": "2",
      "int1": "10",
      "int2": "67",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416046",
      "nombre": "Carana Rodriguez, Genaro David",
      "p1": "7",
      "p2": "4",
      "rec1": "9",
      "int1": null,
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418833",
      "nombre": "Cardetti, Lucas Luis",
      "p1": "7",
      "p2": "6",
      "rec1": "9",
      "int1": null,
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416916",
      "nombre": "Castro, Ezequiel",
      "p1": "6",
      "p2": "6",
      "rec1": "64",
      "int1": null,
      "int2": null,
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416507",
      "nombre": "Cena, Mariano Matias",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "96099",
      "nombre": "Chavarria Ortiz, Emiliano",
      "p1": "8",
      "p2": "4",
      "rec1": "8",
      "int1": "9",
      "int2": "8",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416709",
      "nombre": "Ciampichetti, Valentina",
      "p1": "6",
      "p2": "84",
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "402475",
      "nombre": "Cisneros, Ignacio",
      "p1": "6",
      "p2": "2",
      "rec1": "8",
      "int1": "9",
      "int2": "8",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417332",
      "nombre": "Cornejo Reyes, Zahira Yamila",
      "p1": "7",
      "p2": "9",
      "rec1": null,
      "int1": null,
      "int2": "84",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416138",
      "nombre": "Cotignola, Ursula",
      "p1": "4",
      "p2": "2",
      "rec1": "2",
      "int1": "9",
      "int2": "67",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "400922",
      "nombre": "Cruz Herrera, Samuel Andres",
      "p1": "8",
      "p2": "9",
      "rec1": "10",
      "int1": null,
      "int2": "9",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417846",
      "nombre": "Díaz, Juan Cruz",
      "p1": "7",
      "p2": "4",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "420755",
      "nombre": "Dominguez, Camila Magali",
      "p1": "4",
      "p2": "4",
      "rec1": "10",
      "int1": null,
      "int2": "48",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "422146",
      "nombre": "Duarte, Jonathan Ismael",
      "p1": "9",
      "p2": "4",
      "rec1": "9",
      "int1": null,
      "int2": "48",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "420346",
      "nombre": "Espinosa Soto, Agustina Itati",
      "p1": "6",
      "p2": "4",
      "rec1": "10",
      "int1": null,
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416752",
      "nombre": "Fabbro, Santino Gabriel",
      "p1": "4",
      "p2": "2",
      "rec1": "4",
      "int1": "10",
      "int2": "48",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417486",
      "nombre": "Fanucchi, Felipe Andres",
      "p1": "6",
      "p2": "4",
      "rec1": null,
      "int1": "9",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "79118",
      "nombre": "Feltes, Agustin Tomas",
      "p1": "8",
      "p2": "4",
      "rec1": "4",
      "int1": "10",
      "int2": "48",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416683",
      "nombre": "Fernandez, Agustina",
      "p1": "4",
      "p2": "2",
      "rec1": "8",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418032",
      "nombre": "Figueroa Costamagna, Dalmiro Homero",
      "p1": "6",
      "p2": "2",
      "rec1": "6",
      "int1": "9",
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "414484",
      "nombre": "Galli Vayssettes, Valentina",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417158",
      "nombre": "Garat, Juan Francisco",
      "p1": "2",
      "p2": "84",
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418389",
      "nombre": "Gárate García, Juan Ignacio",
      "p1": "4",
      "p2": "6",
      "rec1": "7",
      "int1": "10",
      "int2": "8",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "422539",
      "nombre": "García Torrez, Alex Willian",
      "p1": "6",
      "p2": "4",
      "rec1": "4",
      "int1": "10",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "84079",
      "nombre": "Garcia, Aldana Selene",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "419111",
      "nombre": "Gauna, Mariano Sebastian",
      "p1": "4",
      "p2": "2",
      "rec1": "2",
      "int1": "9",
      "int2": "67",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416670",
      "nombre": "Gimenez, Giuliana Macarena",
      "p1": "4",
      "p2": "4",
      "rec1": "9",
      "int1": null,
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416884",
      "nombre": "Godoy Vicente, María Constanza",
      "p1": "7",
      "p2": "4",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416978",
      "nombre": "Grimaldi Cairo, Juan Leon",
      "p1": "2",
      "p2": "4",
      "rec1": "7",
      "int1": "48",
      "int2": null,
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "422427",
      "nombre": "Gutiérrez, Luciano Martín",
      "p1": "6",
      "p2": "6",
      "rec1": "9",
      "int1": null,
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "408413",
      "nombre": "Gutierrez, María Candela",
      "p1": "7",
      "p2": "8",
      "rec1": "9",
      "int1": null,
      "int2": "8",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "87905",
      "nombre": "Hilares Ramos, Egyber",
      "p1": "7",
      "p2": "6",
      "rec1": "10",
      "int1": null,
      "int2": "8",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "96151",
      "nombre": "Jaime Quinteros, Gabriel Dilan",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416953",
      "nombre": "Laguía Voglino, Camila",
      "p1": "4",
      "p2": "4",
      "rec1": "48",
      "int1": null,
      "int2": null,
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416951",
      "nombre": "Lescano, Pedro Nahuel",
      "p1": "4",
      "p2": "4",
      "rec1": "9",
      "int1": null,
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417481",
      "nombre": "Lloret Mosmann, Maria Justina",
      "p1": "8",
      "p2": "4",
      "rec1": "9",
      "int1": null,
      "int2": "48",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "422339",
      "nombre": "Lucas Delgado, Braian Roberto Matías",
      "p1": "4",
      "p2": "2",
      "rec1": "2",
      "int1": "9",
      "int2": "67",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "419521",
      "nombre": "Lujan, Abril",
      "p1": "2",
      "p2": "84",
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417100",
      "nombre": "Luna, Jeronimo",
      "p1": "6",
      "p2": "2",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417147",
      "nombre": "Mallo Distefano, Ignacio Alejandro",
      "p1": "7",
      "p2": "8",
      "rec1": "9",
      "int1": null,
      "int2": "8",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "420532",
      "nombre": "Marozzi, Felipe",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "413682",
      "nombre": "Mendoza, Elio Lautaro",
      "p1": "4",
      "p2": "2",
      "rec1": "2",
      "int1": "9",
      "int2": "67",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418800",
      "nombre": "Nieto, Agostina",
      "p1": "6",
      "p2": "6",
      "rec1": "9",
      "int1": null,
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418118",
      "nombre": "Olea, Joaquin Nicolas",
      "p1": "7",
      "p2": "6",
      "rec1": "9",
      "int1": null,
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417098",
      "nombre": "Ortiz Oviedo, Lucas Nicolas",
      "p1": "4",
      "p2": "2",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418646",
      "nombre": "Paez, Juliana",
      "p1": "4",
      "p2": "2",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417958",
      "nombre": "Patteri, Maximo Francesco",
      "p1": "9",
      "p2": "6",
      "rec1": "64",
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418480",
      "nombre": "Paz Salinas, Marcos Gabriel",
      "p1": "6",
      "p2": "84",
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416728",
      "nombre": "Peuser, Ramiro",
      "p1": "4",
      "p2": "2",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418921",
      "nombre": "Possetto, Gianella Abigail",
      "p1": "7",
      "p2": "4",
      "rec1": "9",
      "int1": null,
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416236",
      "nombre": "Prado Vidal, Alma Alexia",
      "p1": "7",
      "p2": "2",
      "rec1": "2",
      "int1": "9",
      "int2": "67",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "96483",
      "nombre": "Raygal Gutarra, Azucena del Pilar",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "419917",
      "nombre": "Riganti, Federico Martin",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "419108",
      "nombre": "Rivero, Juan Augusto",
      "p1": "4",
      "p2": "2",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417970",
      "nombre": "Rojas Contreras, Alesio Luciano",
      "p1": "2",
      "p2": "10",
      "rec1": null,
      "int1": null,
      "int2": "84",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416767",
      "nombre": "Romero Soliz, Hamil Paul",
      "p1": "6",
      "p2": "4",
      "rec1": "4",
      "int1": "10",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417449",
      "nombre": "Rumualdo, Pilar",
      "p1": "6",
      "p2": "6",
      "rec1": "9",
      "int1": null,
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418720",
      "nombre": "Sahade, Ana Milagros",
      "p1": "6",
      "p2": "2",
      "rec1": "2",
      "int1": "9",
      "int2": "67",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417706",
      "nombre": "Sanchez, Manolo",
      "p1": "4",
      "p2": "2",
      "rec1": "2",
      "int1": "67",
      "int2": null,
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "409720",
      "nombre": "Saravia Ursic, Alma María",
      "p1": "6",
      "p2": "6",
      "rec1": "64",
      "int1": null,
      "int2": null,
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418117",
      "nombre": "Schere, Nicolás",
      "p1": "7",
      "p2": "4",
      "rec1": "6",
      "int1": "10",
      "int2": "8",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416655",
      "nombre": "Soria, Mateo",
      "p1": "4",
      "p2": "2",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "416425",
      "nombre": "Suarez Ferrero, Ana Paula",
      "p1": "4",
      "p2": "2",
      "rec1": "4",
      "int1": "9",
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "419526",
      "nombre": "Tarifa Mancilla, Jonathan",
      "p1": "4",
      "p2": "2",
      "rec1": "2",
      "int1": "9",
      "int2": "67",
      "regProfesor": "Promocion TP",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "418324",
      "nombre": "Tejo Hunziker, Santiago",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "421942",
      "nombre": "Tello Gaya, Maria Antonella",
      "p1": "4",
      "p2": "4",
      "rec1": "9",
      "int1": null,
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "420678",
      "nombre": "Tintilay, Guillermo Ezequiel Jesus",
      "p1": "7",
      "p2": "6",
      "rec1": "10",
      "int1": null,
      "int2": "8",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "99545",
      "nombre": "Tobares, Lucas",
      "p1": "9",
      "p2": "4",
      "rec1": "4",
      "int1": "48",
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417353",
      "nombre": "Torres, Florencia Alejandra",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "401065",
      "nombre": "Uez, Bruno",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "85753",
      "nombre": "Ugarte Terceros , Fernando Jose",
      "p1": "50",
      "p2": null,
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "412692",
      "nombre": "Vargas Nieva, Macarena Ariadna",
      "p1": "4",
      "p2": "4",
      "rec1": "9",
      "int1": null,
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "421012",
      "nombre": "Velez Bernis, Nazarena",
      "p1": "2",
      "p2": "84",
      "rec1": null,
      "int1": null,
      "int2": null,
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "417915",
      "nombre": "Zarate Cortez, Maia Rosario",
      "p1": "7",
      "p2": "2",
      "rec1": "6",
      "int1": "9",
      "int2": "7",
      "regProfesor": "Ap. Directa",
      "regAsistencia": "Regular"
    },
    {
      "legajo": "419849",
      "nombre": "Zeballos Casini, Enzo",
      "p1": "4",
      "p2": "4",
      "rec1": "9",
      "int1": null,
      "int2": "48",
      "regProfesor": "Regular",
      "regAsistencia": "Regular"
    }
  ]
};
